version: '3'

services:
  api:
    image: scrooge-api
    volumes:
      - ./api:/app
    depends_on:
      - mongo
    ports:
      - 8080:8080

  bot:
    image: scrooge-bot
    volumes:
      - ./bot:/app
    depends_on:
      - api

  redis:
    image: redis:6.2.6
    command: redis-server --save 60 1
    volumes:
     - ./redis:/data

  mongo:
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASS}"
      MONGO_DB: "${MONGO_DB}"
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASS: "${MONGO_PASS}"
    volumes:
      - ./mongo:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ROOT}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASS}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_ROOT}:${MONGO_ROOT_PASS}@mongo:27017/"
    depends_on:
      - mongo
