version: '3'

services:
  api:
    image: scrooge-api
    volumes:
      - ./api/.env:/app/.env
    networks:
      - web
      - internal
    restart: always

  bot:
    image: scrooge-bot
    volumes:
      - ./bot/.env:/app/.env
    networks:
      - web
      - internal
    restart: always

  cron:
    image: scrooge-cron
    networks:
      - internal
    depends_on:
      - api
    restart: always

  redis:
    image: redis:6.2.6
    command: redis-server --save 60 1
    volumes:
     - ./redis:/data
    networks:
      - internal
    restart: always

  mongo:
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASS}"
      MONGO_DB: "${MONGO_DB}"
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASS: "${MONGO_PASS}"
    volumes:
      - ./mongo:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - internal
    restart: always


networks:
  internal:
    internal: true
  web:
    internal: false