version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./userfile:/etc/traefik/usersfile
  
  api:
    image: scrooge-api
    volumes:
      - ./api:/app
    labels:
      - "traefik.http.routers.api.rule=Host(`${API_HOST_DEV}`)"
      - "traefik.docker.network=scrooge_v2_web"
      - "traefik.http.middlewares.apiAuth.basicauth.usersfile=/etc/traefik/usersfile"
      - "traefik.http.routers.api.middlewares=apiAuth@docker"

  app:
    image: scrooge-app
    volumes:
      - ./app:/app
    labels:
      - "traefik.http.routers.app.rule=Host(`${APP_HOST_DEV}`)"
      - "traefik.http.routers.app.middlewares=apiAuth@docker"

  bot:
    image: scrooge-bot
    volumes:
      - ./bot:/app

  mongo:
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASS}"
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ROOT}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASS}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_ROOT}:${MONGO_ROOT_PASS}@mongo:27017/"
