version: '3'

services:
  api:
    image: scrooge-api
    volumes:
      - ./api:/app
    labels:
      - "traefik.http.routers.api.rule=Host(`${API_HOST_DEV}`)"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    depends_on:
      - mongo

  app:
    image: scrooge-app
    volumes:
      - ./app:/app
    labels:
      - "traefik.http.routers.app.rule=Host(`${APP_HOST_DEV}`)"
    networks:
      - proxy
    depends_on:
      - api

  bot:
    image: scrooge-bot
    volumes:
      - ./bot:/app
    networks:
      - proxy
    depends_on:
      - api

  mongo:
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASS}"
      MONGO_DB: "${MONGO_DB}"
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASS: "${MONGO_PASS}"
    volumes:
      - ./mongo:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - 27017:27017
    networks:
      - proxy

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_ROOT}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASS}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_ROOT}:${MONGO_ROOT_PASS}@mongo:27017/"
    networks:
      - proxy
    depends_on:
      - mongo

networks:
  proxy:
    name: proxy